### ISSUE TITLE
Add stats page

### ISSUE THREAD

**Issue by philippbayer** [openSNP/snpr#102]
As Samantha proposed on the mailing list, we should have a stats page showing # users, # genotypings (with percentage of each provider etc.), some graphs over time etc.

**Comment by tsujigiri** [comment]
...the current time between adding a genotype and parsing it... ;)

**Comment by gedankenstuecke** [comment]
We now have some code to [generate nice graphs based on the data in openSNP](https://github.com/openSNP/opensnp_misc). Should we just write a small cronable rake-task that gets the data and runs the R-scripts daily or so, in order to have updated statistics on the website?

**Comment by philippbayer** [comment]
We could even put that code into a Knitr document, so we can build a static web-site with some additional writing ("the average user enters X user-phenotypes")

Here's an example HTML: https://github.com/yihui/knitr-examples/blob/master/003-minimal.Rhtml

There's then [Kumquat](https://github.com/kickstarter/kumquat) which is a gem that allows Rails to render Rmarkdown via Knitr... wonder whether that would be the best option? then we wouldn't need the cron/rake task, the page would be regenerated, and would always be up-to-date

**Comment by gedankenstuecke** [comment]
Sure, we could go really overboard and generate the graph each time, but I think that's overkill. Because in that case each reload would trigger getting all genotypes/users to generate the raw data for the graph, right? 

The cron solution would just run DB queries as often as we run the cron-job. And I think doing the graph once a day, when the latest DB dump is generated, would be more than fine?

**Comment by philippbayer** [comment]
You're right, it would be against keeping it simple - plus we'd have one more dependency which'll break once the next Rails is out, and at some point die completely, cron is good!

**Comment by gedankenstuecke** [comment]
Yes, already adding R + the required libraries could be tricky at some point. But on the web-front it would be just embedding an image which is static, so it can be easily replaced and in the worst case it will not get updated. 

Now I just need to figure out how we can add R + ggplot2 + reshape2 to the Docker image. Any recommendations on that, especially @tsujigiri? :smile:

**Comment by tsujigiri** [comment]
I don't think we actually need to add it to the image. Why not run it wherever and put the images on the storage box where they are pulled from by the page?

**Comment by gedankenstuecke** [comment]
Sure, that would work as well, but has the problem that one of us has to remember to do it regularly? :wink:

**Comment by tsujigiri** [comment]
We can still use cron.

**Comment by gedankenstuecke** [comment]
ah, ok. you mean having a separate image for running the viz scripts, sorry, I got that wrong!

**Comment by gedankenstuecke** [comment]
I had some success in getting it up and [running with a premade R-docker image](https://github.com/openSNP/opensnp.org-docker/issues/4). 

(btw. is there some easy way to reference issues/requests from other repos?)

**Comment by tsujigiri** [comment]
openSNP/snpr#102

**Comment by gedankenstuecke** [comment]
sweet, thanks!

**Comment by gedankenstuecke** [comment]
I started implementing [this in a branch here](https://github.com/gedankenstuecke/snpr/tree/rplots). :smile: :sparkles:
