### ISSUE TITLE
Redis::ProtocolError: Got ' ' as initial reply byte.

### ISSUE THREAD

**Issue by tsujigiri** [openSNP/snpr#120]
Since this is happening in the workers, I guess we need a separate Redis connection for each instance (as in instance of the worker's class) to fix this.

**Comment by philippbayer** [comment]
I believe this has stopped happening - possibly due to a system update.

    grep "initial reply byte" /var/log/docker/container*

doesn't print anything on web or sidekiq. :+1: for close

We have different sidekiq errors now due to the connection between sidekiq and web dropping out, we can't fix that

**Comment by gedankenstuecke** [comment]
agree :+1:
