### ISSUE TITLE
Bug in Variations you did not enter

### ISSUE THREAD

**Issue by duartemolha** [openSNP/snpr#176]
Hi
when in the section "Variations you did not enter", when you initially click on one (in thie case Astigmatism) I am greeted with a popup where you can either write a text to describe your variation or choose from the list below.

I initially clicked one of the options and the free text option on top disappeared. However, after reading the options I decided none of them really described my phenotype correctly so because I wanted to use the free text option I closed the popup without clicking OK

When I clicked on Astigmatism option again the free-text option would not show up again and one the multiple choice options was selected.

I believe if the user does not click ok and navigates out of the popup, the multiple choice he innitialy clicked should not be accepted as valid and thus when navigating back to the variation, the free-text option should be visible.

**Comment by tsujigiri** [comment]
Thank you very much for reporting this! You earned +1 bug reporting karma. :) One of us will look into it as soon as he finds the time.

**Comment by duartemolha** [comment]
you're welcome.

**Comment by gedankenstuecke** [comment]
This bug even goes a bit further, because it removes **all** free-text input fields as I've just found out. This is due to the fact that we do a blanket `$('input[type=radio]').click(function()` in the view, without specifying to what the button should belonging to. 

So fixing that might be a bit more complicated?

**Comment by 7yl4r** [comment]
I think this code snippet is all that is needed, but I'm not sure what file it should go in (I'm unfamiliar with ruby project layout). 

```javascript
$('.close').click(function(){
    $('input[type=text]').show();
})
```

**Comment by gedankenstuecke** [comment]
I guess that could go into [`app/views/user_phenotypes/_form.html.erb`](https://github.com/openSNP/snpr/blob/67ff132c3b97a9c626d4a4c07a520c8e37ed3d7f/app/views/user_phenotypes/_form.html.erb)? But I assume that @tsujigiri has a better idea of how to correctly do it 😉

**Comment by gedankenstuecke** [comment]
Ah, thanks. Do we already have a Issue open for that?

**Comment by tsujigiri** [comment]
Not that I know of.

**Comment by 7yl4r** [comment]
@gedankenstuecke : can you tell me how to reproduce this bug "remove[ing] all free-text input fields"? Looking [this line](https://github.com/openSNP/snpr/blob/67ff132c3b97a9c626d4a4c07a520c8e37ed3d7f/app/views/user_phenotypes/_new.html.erb#L34) I wouldn't expect that behavior, and if it is true there may be more to this bug than I originally thought. @tsujigiri rightly suggested I be more specific with my jquery selector, but then that won't address the other affected text fields.

**Comment by gedankenstuecke** [comment]
@7yl4r: Yes, I think the issue reported here is another one: After logging in there will be a list of phenotypes you've not entered yet. If you click on the button to add new ones the modal will open giving you the different options.

![screen shot 2016-12-28 at 11 38 00](https://cloud.githubusercontent.com/assets/674899/21520113/4a84c014-ccf2-11e6-9862-4c81a6430f76.png)

Once you click on one of the radio buttons the free-text input field in the modal will disappear. 

![screen shot 2016-12-28 at 11 38 05](https://cloud.githubusercontent.com/assets/674899/21520148/8b30d86e-ccf2-11e6-9209-0e2a827555c9.png)

Now, if you close that modal and open it again the free text field will stay hidden and there's no way to get it back. Does that help? 😄
