### ISSUE TITLE
Foreign key constraints

### ISSUE THREAD

**Issue by tsujigiri** [openSNP/snpr#209]
In order to improve consistency in the database we should add foreign key constraints. There is even [a handy migration function for that](http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_foreign_key). For that to work out, the data needs to be checked and cleaned up where necessary before, though.

**Comment by philippbayer** [comment]
So far we only have a foreign key constraint between UserSnp and Snp via snp_name.

We'd need to add one for each connection - so between SnpReference and both Snp and type of the paper via snp_name, between UserAchievement and User via user_id, via Genotype and UserSnp via genotype_id, UserPicturePhenotype and User via user_id, and all the comments and their respective source via IDs.

Does add_foreign_key do any checks when you add the keys for the first time? Or do we have to write a migration that deletes any dangling connection first? I'd assume it's the second

P.S.: As a generic Rails question - so foreign keys are an additional optional method to make has_many/has_one connections more stringent so we don't have dangling DB-entries? Or why do we add them?

**Comment by tsujigiri** [comment]
They are a database/Postgres thing and ensure consistency on a database level, which Rails sometimes cannot provide. Especially in environments where you have more than one instance running. And yes, we would need to clean the data before we add the constraints, otherwise postgres will complain when creating the constraints (and not do it). The question is basically, do we want to create more work for us in order to have consistent data at all times, or are we ok as it is.

**Comment by philippbayer** [comment]
I'm for fixing it first - the database is going to be smaller and we can guarantee that there's no potentially private data left dangling in the database from deleted users/genotypings/crashed jobs

**Comment by philippbayer** [comment]
Has been merged
