### ISSUE TITLE
Mediawiki warning clogging up the logs

### ISSUE THREAD

**Issue by philippbayer** [openSNP/snpr#234]
Error is: 

    MediaWiki::APIError: API error: code 'warning', info 'API warning: Formatting of continuation data will be changing soon. To continue using the current formatting, use the 'rawcontinue' parameter. To begin using the new format, pass an empty string for 'continue' in the initial query.'

Related issue in the gem:

https://github.com/jpatokal/mediawiki-gateway/issues/69

Issue-page says there's an "official" mediawiki gem now at https://github.com/wikimedia/mediawiki-ruby-api so the gem we're using is likely to be deprecated and won't be "fixed"

So we can do two things:

a) just put in the :ignorewarnings => true into the MediaWiki::Gateway.new call (dodgy, may hide important other warnings)
b) switch to the new gem (possibly harder, but better for future, good to already have tests :P)

Any votes?

**Comment by philippbayer** [comment]
See #217  

TIL: if you have a PR open for a branch (in this case master) github of course adds your new commits to that PR instead of opening a new one :dizzy_face:

**Comment by gedankenstuecke** [comment]
#217 did not fix this, as @philippbayer reversed the changes, so we still need to switch or ignore warnings.

**Comment by gedankenstuecke** [comment]
This is now done thanks to #257, right?

**Comment by philippbayer** [comment]
Yes, this particular issue is done
