### ISSUE TITLE
Moving repository to an organisational structure?

### ISSUE THREAD

**Issue by gedankenstuecke** [openSNP/snpr#248]
Should we set one up and do this or not? Any good reasons for (not) doing so?

**Comment by tsujigiri** [comment]
I'm for it. Looks more professional... if this is what we want. ;)

**Comment by gedankenstuecke** [comment]
Yeah, also it's less connected to one person, which is a good thing imho. Also we could have a single entry point for the docker stuff, the docu-repo etc. 

For that to work we would have to make all links in the README etc. either relative links or switch them to the new repo though. Do relative links work here?

**Comment by tsujigiri** [comment]
No idea. Let's move everything and fix it later. ;)

**Comment by gedankenstuecke** [comment]
Okay, I can do it after lunch :)

**Comment by tsujigiri** [comment]
:+1:

**Comment by gedankenstuecke** [comment]
Created the organization already nevertheless so you can join in, send out the invites.

**Comment by tsujigiri** [comment]
Can you add a subscription, so I can move the private repo ([opensnp.org-ops](https://github.com/tsujigiri/opensnp.org-ops))?

**Comment by gedankenstuecke** [comment]
Adding would mean we would have to pay USD25 per month, do you think that's worth it?

**Comment by tsujigiri** [comment]
Isn't that 7 EUR? Or is it more for organizations?

**Comment by tsujigiri** [comment]
In that case I can keep it.

**Comment by gedankenstuecke** [comment]
It's [more for organizations](https://github.com/pricing), so I would say you keep it for now, because USD 25 is a bit much just for having our deployment documentation somewhere I'd say.

**Comment by tsujigiri** [comment]
Agreed.

**Comment by philippbayer** [comment]
Sounds good to me

**Comment by gedankenstuecke** [comment]
Okay, I've moved it. It seems that github reroutes all old "/gedankenstuecke/" to "/openSNP/" now, for now we should be fine. I'm not sure though what happens if I try to fork it now :D
