### ISSUE TITLE
Fitbit will switch to OAuth 2.0

### ISSUE THREAD

**Issue by gedankenstuecke** [openSNP/snpr#252]
Fitbit [will switch to OAuth 2.0](https://community.fitbit.com/t5/Web-API/OAuth-2-0-is-official-OAuth-1-0a-is-deprecated/m-p/983800#U983800) soon and unfortunately it seems that the [Gem we're using](https://github.com/whazzmaster/fitgem) for interacting with their API will not be upgraded. 

This means we either can decide to remove fitbit from openSNP, switch to another Gem or in the worst case could try to somehow do it ourselves. 

How do you feel about this?

**Comment by philippbayer** [comment]
There's a "generic" oauth2 gem which should work with the Fitbit API, it's just a bit more work to get it to run: https://github.com/intridea/oauth2

**Comment by gedankenstuecke** [comment]
I think the biggest problem is not handling OAuth but rather all the other stuff :wink: Doing the subscriptions for their push-API etc. This is why I wondered whether we should switch to a different gem instead of doing it from scratch?

**Comment by tsujigiri** [comment]
I suppose it's less about *whether* we should switch to a different gem than *if there is* any other gem that does all that.

See: https://github.com/search?l=Ruby&q=fitbit+oauth2&ref=searchresults&type=Repositories&utf8=%E2%9C%93

Let's check these out.

**Comment by gedankenstuecke** [comment]
Good idea, I also saw that fitgem should in principle work with [omniauth](https://github.com/tkgospodinov/omniauth-fitbit), and this seems to have been updated to Oauth2, so maybe we could keep fitgem but switch to omniauth for the authentification?

**Comment by tsujigiri** [comment]
We should check if it does more than authenticating the user with his fitbit account, though. Wouldn't be too useful for us I suppose.

**Comment by gedankenstuecke** [comment]
Yep, at least it looks like it doesn't much else on first look. :smile:

**Comment by SXibolet** [comment]
Despite "no longer being under active development", [fitgem](https://github.com/whazzmaster/fitgem) 1.0 appears to now support `oauth2`.

**Comment by gedankenstuecke** [comment]
That's good news. Have you already started working on seeing whether it works? ✨

**Comment by philippbayer** [comment]
This is now moot

**Comment by gedankenstuecke** [comment]
💜👍
