### ISSUE TITLE
Database seeds seem broken

### ISSUE THREAD

**Issue by tsujigiri** [openSNP/snpr#253]
For some reason the seeds don't get seeded as reliably as they should, lately. Investigate! :mag: :shipit:

**Comment by philippbayer** [comment]
From googling around, it looks like the seeds aren't loaded by default in RSpec, and it seems that the only RSpec test that depends on achievements  - delete_genotype_spec.rb - was only added on 2015-12-31, so could it be that it was never seeded?

**Comment by tsujigiri** [comment]
I think how it's supposed to work ist that by running `rake db:setup`, the db is seeded. The tests run in transactions, so whatever is in the database before, is available in the tests and afterwards. I'm not 100% sure what happens in the tests where we have `DatabaseCleaner` truncate the database, though. Might be a first lead.

**Comment by tsujigiri** [comment]
It turns out you can exclude tables from the cleaning. See [the docs](https://github.com/DatabaseCleaner/database_cleaner#how-to-use).

**Comment by philippbayer** [comment]
Even on my own system the forced-fix of reloading the seeds doesn't work every time I run rake test
