### ISSUE TITLE
Update Bootstrap

### ISSUE THREAD

**Issue by gedankenstuecke** [openSNP/snpr#264]
While working on #102 I once again noticed that we're so far not playing really nice with mobile devices/small screens as the navbar just cuts of stuff. I think we should fix this and while we're at it we could also update the Bootstrap version we're using, as it's super old and at least I couldn't see any obvious way to make it more responsive. 

Do you think this is a worthwhile task?
- [x] Replace old Bootstrap (2.1 iirc) with a more current version
- [x] Make things responsive 
- [ ] Test that things still look niceish :wink:

**Comment by tsujigiri** [comment]
Sure. :+1:

**Comment by qfma** [comment]
Also, bootstrap 4 is currently in development (may still be a while). It may be worthwhile though checking out how much work it would be to port this from 2 -> 4.

**Comment by gedankenstuecke** [comment]
@qfma Do you think it would be work in vain to upgrade to the current Bootstrap version? :smile:

**Comment by vivekiitkgp** [comment]
The version 4 is supposed to be a major rewrite of the previous version and will work only IE9+ and iOS 7+. So, first decision to make is the kind of browser support we wish to retain for openSNP.org website. If we decide to go with v3, later on (it'll be a while though) migrating to v4 will practically be a major refactor.

**Comment by philippbayer** [comment]
I think this would be (possible) part of @MateusJabour's project?

**Comment by gedankenstuecke** [comment]
Yep, I think that will be part of it. We also might want to skip Bootstrap in total, if that seems more appropriate. 😄

**Comment by tsujigiri** [comment]
Keeping Bootstrap would be good because it is well documented and can be operated by developers. :smile: We don't have to stick to the default styles, though. Bootstrap is flexible enough so you can make it look like anything.

**Comment by MateusJabour** [comment]
@gedankenstuecke I'm using the bootstrap v3.3.6, I'm using a mobile first method to write the website, this way we can make it responsive. If you want me to use the Bootstrap 4, it's fine for me, I will just need to make a few changes on the project, since I've done some of it :smile:

**Comment by MateusJabour** [comment]
@vivekiitkgp nice idea, I will look forward to it.
