### ISSUE TITLE
GSoC Students?

### ISSUE THREAD

**Issue by gedankenstuecke** [openSNP/snpr#267]
The Open Bioinformatics Foundation is running as [a hosting organization in this years Summer of Code](https://github.com/obf/GSoC/) and they would take in openSNP related project ideas if we get two mentors to mentor a student. According to Google the time requirements for mentoring is 5h / week. I'd be up for doing it, but I'd need someone to join me on this if we want to do it. 

We also would have to write a project idea, but that shouldn't be an issue, as there are lots of open issues which could be put into a coherent project (at least I think so). Students can apply until 25th of March, so we should hurry up with this. If we can't make it I'll close the issue ;-)

To-Do: 
- [x] Find Mentor #1: Bastian
- [x] Find Mentor #2: Philipp
- [x] Define Project for the student

Please, also let me know if you've no interest/time and/or think it's a bad idea!

**Comment by philippbayer** [comment]
I'd probably not be the most useful mentor due to extreme time difference - both mentors in +/- the same timezone would be much better, and fairer to the student involved

**Comment by gedankenstuecke** [comment]
I actually would have thought the other way around: Unless the student is located in your or my timezone (which I would deem a bit unlikely) they could take use of the TZ difference because one of us is likely to be around?

**Comment by philippbayer** [comment]
That's true, if the student is closer to my time-zone it would be useful - do we both have to be in all meetings with the student?

**Comment by gedankenstuecke** [comment]
Nope, I think it's two so that there's a backup in case one person is busy. :smiley:

**Comment by philippbayer** [comment]
That would make sense, you can add me :)

**Comment by gedankenstuecke** [comment]
Ok, then we'll now need to think about a topic for the student. Any ideas? :smiley:

**Comment by philippbayer** [comment]
I think a "novel" feature (possibly open-ended) would be more exciting for potential students than fixing an old one, or digging in legacy functions. Have a look at the past accepted Biopython projects: http://biopython.org/wiki/Google_Summer_of_Code#Past_Accepted_Projects 

All of these are "make or expand this new thing", nothing is "fix this old thing".

In that case, linking SNPs to phenotypes via association would be the most exciting, but it's also the one that needs the biggest amount of work - one new model (learn MVC), a new worker (learn Ruby), a bit of redesign to display additional information (learn ERB), if time permits add recommendify, all of that with at least a minimum of tests (learn RSpec).

Other ideas:
- expand the stats page with more pretty graphs? add information for users in a similar way (you have X SNPs...)?
- add yet another filetype parsing
- revive the pre-defined phenotype system (questionnaire)
- will edit in more

**Comment by gedankenstuecke** [comment]
Yes, I think new features would be ideal for someone who wants to do GSoC, but I'm not sure we have to expect that people aren't already familiar with Rails etc. So we could offer different levels of problems, for people who are already familiar and those who aren't? 

### easy
1. UI-Update: Make openSNP move into the 2010s by having a responsive layout that works nicely with mobile phones (bootstrap update, overhauling graphs). Easy if you are a CSS/design person, medium otherwise

### medium / hard
1. Adding more QuantifiedSelf layers to openSNP: so far we supported Fitbit as a data provider for people who do self-tracking. But there are many others around, like Jawbone, who also offer APIs. By having more data sources we could allow more people to automatically donate their data. Involves finding possible Gems where possible and implementing them into our Rails framework. Medium if you are familiar with OAuth and APIs, hard otherwise. 

### hard
1. Design a phenotype system that allows for questionaries and predefined answers. So far everything is based on free text. While super adaptable for every thing it's a pain to use the data. Having a set of structured and controlled questionaries alongside those free-text answers would improve data usability by 1000%.

**Comment by gedankenstuecke** [comment]
[Started drafting project ideas](https://github.com/openSNP/GSoC/blob/gh-pages/00_ideas.md) on the fork, would be great if we could do the PR to OBF by tomorrow as the schedule is rather tight already :panda_face:

**Comment by philippbayer** [comment]
>Jawbone

Do we have example data/accounts from these new sources? We could also add new phones, my new Samsung for example automatically tracks my step, same for wife's iPhone

>Design a phenotype system

I  could swear I made a massive file with all predefined phenotypes for this, but I can't find it in the `curated_phenotypes` branch, weird. Last commit is 2014 so I forgot everything.

I still have the `proposed_phenotypes.xls` with the four types - "looks", "medical", "personality" (SAT, different IQ tests), and "multiple possible" like allergies, so we'd need at least two different systems - one with binary choices, one with several choices. At least students won't have to come up with the answers, that should be added.

Ideally there would be a "nice" entrance system (web-based or file-based) that lets people add their predefined questionnaires, as we do get contacted by various researchers.

The Recommendify codebase hasn't been touched in 4 years, I'm really surprised it still works! May be something we have to replace at some point.

**Comment by gedankenstuecke** [comment]
Adding phones and maybe apps like [Moves](https://www.moves-app.com/) would be great as well, sure. I have a Misfit Shine and a Jawbone Up that could provide test data for the student. 

For the phenotypes I remember this thing. Was it maybe in a google doc? In any case I added all the information. See https://github.com/openSNP/GSoC/commit/edba981ecf8329ff6fba5ff4ccfc4f42eaf512f3

**Comment by gedankenstuecke** [comment]
Submitted PR to OBF GSoC repo, closed this.
