### ISSUE TITLE
SaintCyr1: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by SaintCyr1** [openSNP/snpr#275]
Hi! I'm Saint Cyr from Côte d'Ivoire(Ivory Coast). I speak french, so excuse my broken english. I'm front end Developper (HTML,CSS and JQUERY). I'm interested by this project because i think it's social and can help many people. Yet, i think that by contribute in this project, i will improve myself. So, tell me how can i help, and i will do it. Thanks.<p><br><blockquote>This issue was created by @SaintCyr1 via <a href='https://mozillascience.org/collaborate'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by philippbayer** [comment]
Hi Saint Cyr! 

Welcome to the project. Have you seen our gitter chat at https://gitter.im/openSNP/snpr ?
You can also have a look at the [CONTRIBUTING.md](https://github.com/openSNP/snpr/blob/master/CONTRIBUTING.md), our [ROADMAP](https://github.com/openSNP/snpr/blob/master/ROADMAP.md) and our [code of conduct](https://github.com/openSNP/snpr/blob/master/CODE_OF_CONDUCT.md). 

We currently got a bunch of people who arrived via Google Summer of Code, so it got a bit busy - if you join the Gitter channel anytime today or tomorrow we can discuss more!

**Comment by gedankenstuecke** [comment]
@SaintCyr1 Thanks a lot for the interest in helping out. There are a couple of front-end issues that could need some love. For example #223 #176 and the more complex #274. If you want to discuss any of those feel free to drop by our gitter channel at gitter.im/openSNP/snpr or ask here in the issues etc. :smile:

**Comment by gedankenstuecke** [comment]
Closing for now, feel free to be in touch if we can help in any way 💖 🎉
