### ISSUE TITLE
Ruby version support

### ISSUE THREAD

**Issue by tsujigiri** [openSNP/snpr#280]
As it came up on the mailing list: Should we specify a Ruby version to use (using a `.ruby-version` file) or should we try to keep everything compatible with at least 2.0 and up or even 1.9.3 and up? The latter has the advantage that there would be one barrier less to get started. We would add all supported versions to the travis build matrix and (hopefully) be done. 2.3 has a few nice features we wouldn't be able to use, but Ruby works fine without them. ;)

**Comment by philippbayer** [comment]
My Fedora's system Ruby is 2.2.5.
The current Ubuntu long-term support release is "Xenial Xerus" and has Ruby 2.3, with the LTS before that still running 1.9.3  ([source](http://packages.ubuntu.com/search?keywords=ruby])). However, the current LTS was only released a month ago so I'm sure that most places running only LTS releases still run the old one. In that case, 1.9.3 and up would probably be the most "inclusive" choice, what do you think?

**Comment by gedankenstuecke** [comment]
I'm with @philippbayer on that one. I guess we can always drop the 1.9.3 support later on when no one is using it any longer (spoken like a true Python-developer).

**Comment by philippbayer** [comment]
Just ran into this problem during `bundle install`:

```
Installing listen 3.1.5
Gem::InstallError: listen requires Ruby version >= 2.2.3, ~> 2.2.
An error occurred while installing listen (3.1.5), and Bundler cannot continue.
Make sure that `gem install listen -v '3.1.5'` succeeds before bundling.
```

So we can't support older Ruby versions without a bit of gem-circumvention magic (listen comes from Guard - do we need Guard?)

**Comment by tsujigiri** [comment]
Guard is nice for development but not essential. The Guard README claims it is "tested against Ruby 1.9.3, 2.0.0, 2.1.0, JRuby & Rubinius". I suppose they will do something about the `listen` dependency eventually. I'd say remove it for now. I'll try re-adding it when I want to use it. ;)

**Comment by tsujigiri** [comment]
FYI: [This happens if we add 1.9 and 2.3 to the TravisCI config.](https://github.com/openSNP/snpr/commit/9e6a92697506f61fc3ce1d7d58c6bdc4194839f0)

**Comment by philippbayer** [comment]
Everything dies :) At least the 2.3 one seems to be fixable, it just dies when it tries to install 2.3. 

1.9 dies with recaptcha too so I'd rather not just support 1.9, that seems to be a bit of a headache, and it just fails at recaptcha - wonder what else fails after recaptcha would work.

Guard's README says to use Ruby >= 2.2.5 only: https://github.com/guard/guard

**Comment by philippbayer** [comment]
Everything dies :) At least the 2.3 one seems to be fixable, it just dies when it tries to install 2.3. 

1.9 dies with recaptcha too so I'd rather not just support 1.9, that seems to be a bit of a headache, and it just fails at recaptcha - wonder what else fails after recaptcha would work.

Guard's README says to use Ruby >= 2.2.5 only: https://github.com/guard/guard

**Comment by audy** [comment]
This would be useful for getting setup for development. I had to dig through `.travis.yml` to find that you were using 2.2.

You could also specify it in the `Gemfile`.

**Comment by philippbayer** [comment]
So the server now uses Ruby 2.3.3, which is also now specified in `.travis.yml`.

We can do two things, let's have a small vote, I want to close this issue today or this weekend:

- specify in Gemfile via `ruby "~> 2.3.0"`
- RVM-way: specify in .`ruby-version`  via `echo 2.3.3 > .ruby-version` (the production server uses RVM too)

I vote for specifying it in the Gemfile, that seems to be the most standard way.

**Comment by gedankenstuecke** [comment]
:+1: for the Gemfile.

**Comment by philippbayer** [comment]
let's just do that then, PR is here https://github.com/openSNP/snpr/pull/376

**Comment by philippbayer** [comment]
that worked!
