### ISSUE TITLE
Layout for email

### ISSUE THREAD

**Issue by gedankenstuecke** [openSNP/snpr#301]
As @tsujigiri pointed out in #300: Our email system is highly repetitive by now. Instead of repeating the footer etc. for each email layout we should implement a backbone layout that's shared amongst all emails and then just plug in the specifics for each.

**Comment by tsujigiri** [comment]
For reference, this is what needs to be touched when removing a sponsor from the emails: https://github.com/openSNP/snpr/pull/341/files
