### ISSUE TITLE
eMails on new phenotypes

### ISSUE THREAD

**Issue by gedankenstuecke** [openSNP/snpr#303]
When a new phenotype is created users can get notified about this via email. But these emails should only be sent if it's a real new phenotype, not when it's a person unknowingly creating an existing phenotype. So far we don't check for this, see  https://github.com/openSNP/snpr/blob/master/app/controllers/phenotypes_controller.rb#L37
and https://github.com/openSNP/snpr/blob/master/app/controllers/phenotypes_controller.rb#L55

Should change the logic that the emails are only sent when the unless part is true.

**Comment by tsujigiri** [comment]
☺
