### ISSUE TITLE
`UserMailer#fitbit_dump` is broken

### ISSUE THREAD

**Issue by tsujigiri** [openSNP/snpr#310]
Sidekiq says "ActionView::Template::Error: undefined method `name' for nil:NilClass".

**Comment by gedankenstuecke** [comment]
Does it give more details on where it's broken? :P

**Comment by philippbayer** [comment]
This comes from the fitbit_dump user_mailer from line 7:

`<b>Hi <%=@user.name%>,</b>`

In other words, this user account has been deleted but it is still trying to send mails to it.

**Comment by gedankenstuecke** [comment]
Let's see whether that's it. I just requested a dump for my own data. So the data as well as the email requesting it should be there :D

**Comment by gedankenstuecke** [comment]
Still failed. 

```
Arguments: "bgreshake@googlemail.com", "/data/fitbit/user1_fitbit_data_201606200840.csv"
Error: ActionView::Template::Error: undefined method `name' for nil:NilClass
```

Seems another issue is at work there.

**Comment by philippbayer** [comment]
Looking at the `fitbit_dump` method in he user_mailer controller, the variable `@user` is never defined

**Comment by gedankenstuecke** [comment]
yep, just saw it myself. will fix it!
