### ISSUE TITLE
Scheduled `recommend` jobs

### ISSUE THREAD

**Issue by tsujigiri** [openSNP/snpr#315]
There is always a high number of `Recommendphenotypes` and `Recommendvariations` jobs in the queue. Since these are triggered whenever a `Phenotype` or `UserPhenotype` is created. In order to free up worker resources, I think we should run them less frequently. What do you think is frequent enough? Once a day? Once a week?

**Comment by gedankenstuecke** [comment]
Once a week sounds reasonable to me!

**Comment by tsujigiri** [comment]
Why do we feed the recommender in `Recommendvariations` `up.phenotype.id.to_s+"=>"+up.variation` instead of just the id?

**Comment by philippbayer** [comment]
```2012-03-16 18:09:30 +0100 32)        @phenotype_array << up.phenotype.id.to_s+"=>"+up.variation```

That's so old, I wonder whether we'll be able to answer that :)

Looking at the [recommendify manual](https://github.com/paulasmuth/recommendify) it's what they do: 

     # add `order_id->product_id` interactions to the order_item_sim input

so you can group phenotypes by phenotype -> user-phenotype interaction?

**Comment by tsujigiri** [comment]
Yes, but I don't get why we would use `up.variation` instead of `up.id`. The ID is unique, the variation isn't. Does that have something to do with duplicate variations?

I also just noticed, that we don't even use the `VariationsRecommender`, other than instantiating it. What's up with that? :smile:

**Comment by philippbayer** [comment]
Oh, no idea :)
I think the VariationsRecommender is still "old cruft" since now you have the JavaScript in the form already tell you about similar variations, but I may be wrong

**Comment by tsujigiri** [comment]
So... should we get rid of it? @gedankenstuecke?

**Comment by gedankenstuecke** [comment]
Okay, I haven't looked into this in a while either. :D But: The VariationsRecommender should do something different from the PhenotypesRecommender or however it's called. 

The VariationsRecommender should list how similar certain phenotypic variations are ("people who give 'over 30' as their BMI-phenotypic variation also give 'high' as their blood pressure") while the other one should only relate phenotypes "people who were willing to tell us their phenotype X also were willing to enter phenotype Y").

Why I went for the ID: I have no clue, I think you want to find the co-occurrence of the same variations, so you want them to be non-unique amongst users? (does that make any sense? feeling rather sleep deprived today)

**Comment by tsujigiri** [comment]
That makes sense, but doesn't explain why we don't use it. :smile:

**Comment by gedankenstuecke** [comment]
Ah, the `VariationRecommender` is used in `app/controllers/phenotypes_controller.rb` (init in line 117 and used in line 138 f.). This is for the page you will get to see after you enter a phenotype. 

So you enter phenotype X, then you get a landing page for recommended phenotypes and recommended phenotype/variation combinations. :-)

**Comment by tsujigiri** [comment]
`@variation_recommender` is defined but never used. Maybe it is intended to be used in line 146 instead of `@phenotype_recommender`?

**Comment by gedankenstuecke** [comment]
Now I see it. Good question. But iirc it at least works somehow even without it? :D

**Comment by tsujigiri** [comment]
Instead of rebuilding the whole thing all the time, couldn't we just add new variations/phenotypes whenever they are created? Even if it diverges from the data in the database, it should still give accurate enough recommendations, no?

**Comment by tsujigiri** [comment]
We would have to re-process the matrix for that one phenotype/variation, of course. On the other hand, reprocessing everything every now and then doesn't exactly exceed our capacity...
