### ISSUE TITLE
Remove Pagination

### ISSUE THREAD

**Issue by gedankenstuecke** [openSNP/snpr#329]
[Following this blog post](https://blog.jooq.org/2016/08/10/why-most-programmers-get-pagination-wrong/) @tsujigiri and I briefly discussed this on _Gitter_: 

The SNP index (and I think all the other index pages as well) doesn't actually need the pagination where you can jump to a given page of SNPs (currently there are 236591 pages…). No one uses them. Instead just offering the ⬅️  ➡️  buttons would be good enough. 

This should a) remove clutter from the index pages and b) make things faster.

**Comment by 7yl4r** [comment]
This should probably be implemented as a feature of [will_paginate](https://github.com/mislav/will_paginate) (or finding an alternative), rather than rolling a custom solution for this project.

**Comment by gedankenstuecke** [comment]
Yep, fully agreed. We should figure out whether there's such a thing that we could just replace our current solution with. 😃

**Comment by audy** [comment]
[ajax-datatables-rails](https://github.com/antillas21/ajax-datatables-rails) is pretty good. I use it for tables with 100,000s of rows. And you get free search.

**Comment by tsujigiri** [comment]
Looks like we only need to add a `page_links: false` to the `will_paginate` call.

https://github.com/mislav/will_paginate/wiki/API-documentation#will_paginatecollection-options

**Comment by gedankenstuecke** [comment]
That sounds good, maybe @7yl4r wants to give it a try, would make a fun first commit 😄

**Comment by 7yl4r** [comment]
I was hoping to get a pull request submitted quickly this morning, but I have had some difficulty getting the project set up. I thought I had everything working (looks fine when loaded on localhost), but `bundle exec rake` fails 52/52 tests. :dizzy_face:

I will get it figured out... eventually.
