### ISSUE TITLE
Mitochondrial SNPs do not work in biodalliance

### ISSUE THREAD

**Issue by philippbayer** [openSNP/snpr#348]
I assume this is because it uses GrCh38 as reference, and there the name of the mitochondrial genome is chrM, not MT, 

Possible solution: have a rake task that replaces all MT with chrM, and change parsing.rb to replace MT with chrM if encountered

Weirdly enough, SNPs with chromosome Y work fine (e.g. https://opensnp.org/snps/rs9645182 ) even though the 'official' name is chrY, not Y

**Comment by philippbayer** [comment]
Example: https://opensnp.org/snps/i4001200

**Comment by nathanhaigh** [comment]
Many tools seem to accept chromosome names with our without the `chr` prefix. That might explain why `chrY` and `Y` work but not `chrM` and `MT`. It would have to be `M` and not `MT`.

**Comment by gedankenstuecke** [comment]
Thanks for the pointer!
