### ISSUE TITLE
Reduce footprint of webpage

### ISSUE THREAD

**Issue by philippbayer** [openSNP/snpr#352]
It costs [$0.15 to visit openSNP in Canada on a mobile device.](https://whatdoesmysitecost.com/test/170425_XY_db0cc54d61b0243bdc82d6f4f763207d#usdCost)

Here are some recommendations on how to reduce openSNP's data footprint: http://www.webpagetest.org/result/170425_XY_db0cc54d61b0243bdc82d6f4f763207d/

- [x] further improve gzip compression, looks like application.js isn't gzipped
- [ ] fix browser caching (max-age currently missing)
- [ ] improve time to first byte, not sure why so extremely slow
- [ ] use CDN for static pics? adds extra costs

Not sure how much of that is fixing stuff in Rails, how much is fixing stuff on the server itself

**Comment by tsujigiri** [comment]
It's pretty fast on my end, but I am currently on a pretty big line. Additionally to the above points we might be able to serve a static version of the "home" page. That's pretty easily done in Rails.

**Comment by philippbayer** [comment]
With Mateus' changes the site costs only [$0.05 in Canada](https://whatdoesmysitecost.com/test/170602_VD_1bed0fabcf5484101b3889f0bce253c1), 10 cents cheaper is pretty good! Think of how much extra maple syrup Candians can afford now!

First byte time is still an F on the test though. perhaps that's a passenger issue?

**Comment by gedankenstuecke** [comment]
Yay! That's cool!

**Comment by philippbayer** [comment]
The time to first byte is still low on that site, but it's hosted in the US and openSNP is in Germany. Other services like https://performance.sucuri.net/domain/opensnp.org have a good Time to First Byte for Europe, as expected, so now I'm closing this issue as Mateus' PR reduced a lot of the footprint
