### ISSUE TITLE
Rework the "About us" FAQ page. 

### ISSUE THREAD

**Issue by gedankenstuecke** [openSNP/snpr#361]
There was a [complaint about the lack of transparency on who's behind openSNP](https://twitter.com/usethespacebar/status/868944361060421632). Right now we only have a small paragraph on that [in our FAQ](https://opensnp.org/faq). So maybe we should elaborate a bit on that, as it might be unclear to newcomers. 

- [x] [Write longer paragraph for *About Us*](https://opensnp.piratenpad.de/about-us)
- [x] Link to that paragraph from the disclaimer page as well.

**Comment by gedankenstuecke** [comment]
Drafted a quick update on the [about us](https://opensnp.piratenpad.de/about-us) which should be more accurate and gives some more details.

**Comment by philippbayer** [comment]
I've added a little bit. How easy is it to find the 'About us' thing for a newcomer?

**Comment by philippbayer** [comment]
I'm not sure where a more prominent place would be - maybe leave these accordion style thingies unfolded so that users don't have to waste a click? some people may not know that you even have to click on the question

**Comment by gedankenstuecke** [comment]
We could make the FAQ-menu item a dropdown as well? And give "FAQ" & "About us" there?

**Comment by philippbayer** [comment]
That's a good idea!

**Comment by gedankenstuecke** [comment]
@tsujigiri are you fine with the draft for the about page? 🙂

**Comment by gedankenstuecke** [comment]
Will be fixed with #365 :+1:

**Comment by tsujigiri** [comment]
Looks good to me. :+1:

**Comment by gedankenstuecke** [comment]
@tsujigiri btw. I included the GitHub avatars on the page now, for @philippbayer, you and me. If you'd like to use another picture please feel free to go ahead! :)
