### ISSUE TITLE
Update humans.txt

### ISSUE THREAD

**Issue by gedankenstuecke** [openSNP/snpr#366]
I don't want to lose track of this: At the end of the Global Sprint we need to update the humans.txt to include all new contributors! 💖  Thanks to all of you who contribute! 🎉

**Comment by philippbayer** [comment]
People I got here in Perth working on and off on openSNP stuff:

@bverpaalen Brent Verpaalen
@mariusschwarz Armin Scheben
@andreabedini  Andrea Bedini

**Comment by gedankenstuecke** [comment]
![grateful](https://media.giphy.com/media/l0HlRc1y0LKlanwly/giphy.gif)

🎉  Thanks to all of you

**Comment by gedankenstuecke** [comment]
@amiefairs edited our broken language! 💓

**Comment by philippbayer** [comment]
Do we have @robsyme too?

**Comment by gedankenstuecke** [comment]
Not so far, but noted! 👍

**Comment by robsyme** [comment]
Oh, I don't think I should be included here - my contribution to this Sprint was for alethia.

**Comment by gedankenstuecke** [comment]
@robsyme there's still time to change that and help us out as well 😂
