### ISSUE TITLE
(UI) bugs due to frontend overhaul

### ISSUE THREAD

**Issue by gedankenstuecke** [openSNP/snpr#375]
With merging #365 we got some (mainly UI) bugs that we need to tend to:

- [x] Glyphicons in production are broken.
- [x] Avatar for @gedankenstuecke doesn't load on *About Us*
- [x] Modals for entering new phenotypes are white text on white background
- [x] Numbered Pagination came back, see #329 for fix
- [x] "Latest Data"-tab loads forever, ineffective database queries?
- [x] Pie charts for allele/genotype frequencies don't have legend.
- [x] Fitbit graphs are also strange.
- [x] Remove #{@user.name} SNPs on _user_not_user.html.erb
- [x] Remove index-column on index.html.erb for users & genotypes
- [x] Phenotype entry autocompletion is somewhat broken (on modal an phenotype page directly)

Add your own things below 😂

**Comment by gedankenstuecke** [comment]
Replacing my avatar with a PNG instead of JPEG worked. No clue why, should investigate this.

**Comment by gedankenstuecke** [comment]
#379 also closes the broken modals. My bad for not switching branches in time.

**Comment by gedankenstuecke** [comment]
With the UI update #223 seems to be at least a bit better now. The Autocomplete on the modal phenotype entry works if you cycle through it with your arrow keys, but it doesn't show the actual selection in a sensible way so far. Might be some CSS/JS updates that killed it.

**Comment by philippbayer** [comment]
Glyphicons have been fixed, see https://github.com/openSNP/snpr/pull/383

**Comment by gedankenstuecke** [comment]
Yay, thanks! 🙏

**Comment by gvd** [comment]
Regarding the phenotype autocomplete. I see the following code:
    $(function () {
        $("#phenotype_characteristic").autocomplete({
            source: ["Retrognathia (Marfan Syndrome)","Eye pigmentation ","Vegetarianism/Preference for Meat","Form of foot","Eye color","A+","MSG tastes...", "....."]
        });

Which is missing some brackets. It should be:
    $(function () {
        $("#phenotype_characteristic").autocomplete({
            source: ["Retrognathia (Marfan Syndrome)","Eye pigmentation ","Vegetarianism/Preference for Meat","Form of foot","Eye color","A+","MSG tastes...", "....."] }); <----------------
        });

**Comment by gedankenstuecke** [comment]
#411 closes the last one of the bugs reported here so far. 🎉
