### ISSUE TITLE
Deleting messages doesn't work

### ISSUE THREAD

**Issue by gedankenstuecke** [openSNP/snpr#391]
I'm getting an unauthorized when trying to delete a message on the production system.

**Comment by gedankenstuecke** [comment]
Did some research into it: You can delete messages that you sent to yourself, but not messages you received from other people. Seems like the permission check doesn't work any longer.

**Comment by tsujigiri** [comment]
Seems to me like it works perfectly. Just not as intended. :smile: 
https://github.com/openSNP/snpr/blob/master/app/controllers/messages_controller.rb#L46-L55

**Comment by gedankenstuecke** [comment]
And I found out [who's to blame for the change that made it break](https://github.com/openSNP/snpr/blob/cd9f1b9c8f00aac03b33ce6bae93a8d923f9e512/app/controllers/messages_controller.rb#L59). But as we're not having tests for it, it never showed. 😉 

I think the whole check routine on the `destroy` can go, as we're making sure that it's the right user with the `require_user`, right? Will work to fix that and write the tests.

**Comment by tsujigiri** [comment]
I'm not sure if this doesn't require a bit more thought. I'd expect the message to still be visible by the sender, if the recipient deleted it, for example. What do you think?
