### ISSUE TITLE
Discuss: Kicking out Fitbit, using OpenHumans

### ISSUE THREAD

**Issue by gedankenstuecke** [openSNP/snpr#392]
Today @tsujigiri, @madprime and I discussed a bit about the possibility to remove our (broken, see #252) Fitbit integration and replacing it with a far simpler integration of OpenHumans. (context: @tsujigiri and I had discussed the feature creep in openSNP some months back and I think it would be a good opportunity to do so). 

The [OpenHumans API](https://www.openhumans.org/direct-sharing/overview/) allows to easily list all the public data sources that people have. On our end we could use their OAuth2 integration to just link OpenHumans accounts to openSNP accounts. On our end we could just store

1. the OpenHumans username
2. the Public Data sources that this user has on OpenHumans. 

That way we could easily add this two bits of information into our `phenotypes.csv` and people who are really interested in this could easily download the data via the OpenHumans-API, we don't have to fix the Fitbit integration and there's no data duplication going on. What's your take on it? 😄

**Comment by philippbayer** [comment]
:+1:

The Fitbit integration likes to break and this gives us the opportunity to add more data while having to implement only one API integration.

What do we do with the 'old' Fitbit data then? Just delete it all? Keep legacy around?

**Comment by gedankenstuecke** [comment]
I'd say we point people who're having a Fitbit connection set up to OpenHumans and delete the data after some grace period, so that people can backup the data that's on openSNP so far?

**Comment by BenjaminHCCarr** [comment]
I would support this.
line 144 of: view-source:https://opensnp.org/fitbit/info
` <h4><a class="btn btn-info" href="/fitbit/start_auth">Connect your Fitbit account with openSNP</a></h4>`
leads to the errror on https://opensnp.org/fitbit/start_auth of
```
openSNP

500: Something broke.
If it keeps on doing this, please send us an e-mail: {info at opensnp dot org}.
```

**Comment by gedankenstuecke** [comment]
Yeah, that's still of our todo, if someone wants to take on this job prior to me being done with thesis writing: Please go ahead, and be aware that there's a [$5,000 grant opportunity from Open Humans](https://www.openhumans.org/grants/) which could support exactly this work. 💰
