### ISSUE TITLE
Stickers to new contributors

### ISSUE THREAD

**Issue by gedankenstuecke** [openSNP/snpr#395]
This goes to @andreabedini @amiefairs & @bverpaalen: 

I just wanted to say: **Thank you so much** for your great help during the *#mozsprint* last week! 🎉 🍰 

As a small sign of our appreciation I'd love to mail all of you [some of our stickers!](https://github.com/openSNP/Community-Design/blob/master/openSNP/RGB/Sticker.png) Please drop me an email with your address to `bgreshake@gmail.com` and I'll make sure that they are on their way asap. 💖 😍 

![](https://m.popkey.co/93d740/v49wk.gif)

**Comment by andreabedini** [comment]
❤️ I clearly don't deserve any thanks but I'd grab the stickers none the less :-) :envy

**Comment by amiefairs** [comment]
I don't think I deserve it either but I definitely want some stickers :) Thanks!

**Comment by gedankenstuecke** [comment]
@amiefairs happy to send some over. Don't forget to email your address. 😄

**Comment by gedankenstuecke** [comment]
Will go out tomorrow! 🎉
