### ISSUE TITLE
Test Coverage Calculation

### ISSUE THREAD

**Issue by gedankenstuecke** [openSNP/snpr#398]
I'm a bit confused when it comes to that:

Codeclimate says that all of the json part in the `snps_controller.rb` [would not be covered](https://codeclimate.com/github/openSNP/snpr/coverage/59390933f22b7500010ac267). At the same time there's at least some testing going on in [`spec/requests/snps_spec.rb`](https://github.com/openSNP/snpr/blob/master/spec/requests/snps_spec.rb). What am I missing? 😂

**Comment by tsujigiri** [comment]
Running it locally, it looks like the result of the legacy tests overrides the result of the RSpec tests. If I only run RSpec, the code in the controller shows up as covered.

**Comment by philippbayer** [comment]
So is it possible to just delete the legacy test outside of RSpec?

**Comment by tsujigiri** [comment]
We could just not run the coverage reporting in the legacy tests and consider the code not to be covered.  [This](https://github.com/colszowka/simplecov#using-simplecov-for-centralized-config) suggests, that SimpleCov actually supports running multiple test frameworks, though. But I can't seem to get it working.

**Comment by gedankenstuecke** [comment]
Do we have an idea how much of the code base is only covered by the legacy tests?

**Comment by tsujigiri** [comment]
19.9%, according to SimpleCov.

**Comment by tsujigiri** [comment]
41.23% for RSpec.

**Comment by tsujigiri** [comment]
It shows up in the terminal if you run the tests.

**Comment by tsujigiri** [comment]
Not running SimpleCov for the legacy tests turns out to be not as simple as not requiring it in the test_helper.rb.

**Comment by gedankenstuecke** [comment]
So how do we get to 77% for codecoverage if even the nonoverlapping sum is only 60%? :D

**Comment by tsujigiri** [comment]
Codeclimate may have some additional configuration.

**Comment by tsujigiri** [comment]
This seems relevant: https://docs.codeclimate.com/docs/setting-up-test-coverage#section-usage

**Comment by gedankenstuecke** [comment]
Okay, I'll head to the Zürich pride now but will try to have a look tonight 🏳️‍🌈

If you should have time to explore that before feel free 😉

**Comment by gedankenstuecke** [comment]
Despite the changes in #400 it [still gives the json as not covered](https://codeclimate.com/github/openSNP/snpr/coverage/593aa5ac680406000106459f). 😥

**Comment by tsujigiri** [comment]
I doesn't look like the `json` method is used anywhere.

**Comment by gedankenstuecke** [comment]
Ah, you're right. There's two more API calls that need to be tested for that., see `routes.rb` Something to work on during next week!
