### ISSUE TITLE
Links to tabs don't work 

### ISSUE THREAD

**Issue by gedankenstuecke** [openSNP/snpr#406]
Linking to specific tabs doesn't work right now. E.g. `https://opensnp.org/snps/rs7903146#plos` should take you to the PLOS-paper tab, but that doesn't work. 

Same is true for linking to a users personal message page: We're trying to link back to a user's inbox at `https://opensnp.org/users/1#messages` [after sending a message in the `message_controller`](https://github.com/openSNP/snpr/blob/master/app/controllers/messages_controller.rb#L24) but that fails right now. Seems some JS there isn't working as it's supposed to.

**Comment by philippbayer** [comment]
This piece of JavaScript can do it:

<pre>
$(function(){
   var hash = window.location.hash;
   var anchor = $('a[href$="'+hash+'"]');
   if (anchor.length > 0){
      anchor.click();
   }
});
</pre>

[Source](https://stackoverflow.com/a/11333510)

Essentially it checks whether there's a hash in the URL and then 'clicks' the tab for the user. With Firefox's JavaScript Scratchpad it works, will send a PR later

**Comment by gedankenstuecke** [comment]
Ok, looking forward to see that PR! (Tried briefly on my end and it seems to get stuck in an endless loop on Chrome when I just c&p it into `application.js`).

**Comment by philippbayer** [comment]
Done with latest PR
