### ISSUE TITLE
Picture phenotype upload broke

### ISSUE THREAD

**Issue by philippbayer** [openSNP/snpr#416]
Just got a mail, looks like uploading a new picture results in a 404

**Comment by gedankenstuecke** [comment]
That's strange. I just tried for `https://opensnp.org/picture_phenotypes/4` and there it worked. The image uploaded was a plain `.jpg`. Wonder whether this relates to the JPG issue we saw in #375?

**Comment by gedankenstuecke** [comment]
Yep, #455 did close it as expected, needed to use `patch` instead of `post` after all m)

**Comment by philippbayer** [comment]
:+1:
