### ISSUE TITLE
Issues with message system

### ISSUE THREAD

**Issue by gedankenstuecke** [openSNP/snpr#425]
From our emails

>Every time I look down the list of messaging I have sent, the page resets to the top of the list every 10 seconds or so.
>
> So if I do not get to a message within the 10 seconds, there is nothing I can do;
I cannot find the message, I cannot highlight it and I cannot see what I wrote.

Will have to verify and investigate.

**Comment by philippbayer** [comment]
bump this one again,  have been reminded that it still exists

**Comment by tsujigiri** [comment]
It only happens if the messages are accessed via the "Messages" link in the user dropdown at the top. If you go to your user profile and click the "Your messages" tab there, it's fine.

**Comment by philippbayer** [comment]
Can anybody still replicate this issue?

I have a *similar* issue, I made a gif, is that the issue? Or is that new? It essentially refreshes the entire page forever if you go too deep into the messages tab (at least I think that's what triggers it). I can reproduce that in a local dev environment, not sure yet what triggers it.

![output](https://user-images.githubusercontent.com/413885/46589863-26ab1a00-cae1-11e8-872f-0d8ebaefc2a3.gif)
