### ISSUE TITLE
Support for TSV file type

### ISSUE THREAD

**Issue by BenjaminHCCarr** [openSNP/snpr#429]
Compete Genomics (now defunct) was a common whole genome sequencer, which provided `tsv` files in two formats:
`236M   masterVarBeta-ASM.tsv.bz2`
`239M   var-ASM.tsv.bz2`

This was also the provider of sequencing for the @PGPHarvard https://my.pgp-hms.org/

It is possible to convert to `VCF` using `cgatools`:

#Complete Genomics Analysis Tools
### However it is impossible to compile this from source as the source code specifically calls for`BOOST_FILESYSTEM_VERSION 2`

This was a known issue as `cgatools-1.8.0.1-source/cgatools/core.hpp:[43-46]` notes:
```
// Use version 2 of the Boost Filesystem library.
// This stopped being the default as of Boost 1.44 and
// will no longer be supported in Boost 1.48.
#define BOOST_FILESYSTEM_VERSION 2
```
boost is currently at `1.62.0`. `1.48.0` was released in 2011.

Binaries are contained in the Galaxy Toolshed.
---

Little new data is likely to be generated, but for example, all PGP data (public) is in this format.

---

The format is documented, some links:
http://www.completegenomics.com/customer-support/documentation/100357139-2/
Sample Files:
http: http://www.completegenomics.com/public-data/
ftp: [ftp://ftp2.completegenomics.com](ftp://ftp2.completegenomics.com/)
Specifications [pdf] http://www.completegenomics.com/documents/DataFileFormats_Standard_Pipeline_2.2.pdf
https://thegenomefactory.blogspot.com/2016/09/manipulating-big-tsv-files-in-unix.html
https://usegalaxy.org/static/formatHelp.html#mastervar

**Comment by gedankenstuecke** [comment]
Thanks for the pointer. The `masterVarBeta` should be easy enough to parse, as it's just yet another VCF rewrite basically and it should be easy enough to transform this into a `23andMe` style format. Right now I'd say that's probably even the best variant? Because there are not many people who have CG data and as it's defunct there will no one be producing more/new data in that format?

**Comment by gedankenstuecke** [comment]
Given that there's no interest in the files so far I'll close w/o adding the format.
