### ISSUE TITLE
Removing phenotypes does not persist

### ISSUE THREAD

**Issue by abetusk** [openSNP/snpr#436]
When under my "Your Phenotypes" page as a result of clicking on the "Edit Your Phenotypes" in my account dropdown, I am given a list of phenotypes.  If I remove a phenotype by hitting the "Remove" button, it disappears from the list but if I navigate away and navigate back, the item reappears.

Please let me know if you need more specific details of my account or the exact phenotype.

**Comment by philippbayer** [comment]
Hi @abetusk, thanks for reporting! Must be one of those things that fell under the table when we deployed the redesign, we'll have a look asap!

**Comment by philippbayer** [comment]
Hi @abetusk , I finally had some time and I don't think I can reproduce the bug - after you deleted the phenotype, have you clicked 'Update information' after deleting the phenotype? Without clicking that button nothing is saved

**Comment by philippbayer** [comment]
This should fix it
