### ISSUE TITLE
Replace logo of Open Humans integration

### ISSUE THREAD

**Issue by gedankenstuecke** [openSNP/snpr#506]
Open Humans recently changed it's logo, c.f. https://github.com/OpenHumans/logo-open-humans 

We should replace it on our end with the current one to avoid confusion.

**Comment by gedankenstuecke** [comment]
Thanks! :D

**Comment by philippbayer** [comment]
Sorry about the slowness, it's been absolute chaos here :P It's exactly 00:06, child 2 JUST went to sleep, child 1 woke up again hooray

**Comment by gedankenstuecke** [comment]
Haha, no worries! All the best for getting them to sleep at the same time 😉

**Comment by philippbayer** [comment]
:)

**Comment by gedankenstuecke** [comment]
I think the deployment didn't work though 🤔
