### ISSUE TITLE
404 for downloading openSNP data dump and individual genotype data

### ISSUE THREAD

**Issue by joannearcilla** [openSNP/snpr#537]
Hi, currently encountering 404 (Page Not Found) error whenever I try downloading [openSNP's data dump](https://opensnp.org/data/zip/opensnp_datadump.current.zip) or downloading a particular user's genotype data [(sample here)](https://opensnp.org/data/10896.23andme.9009). 

Hoping this could be resolved. Thanks! :)

**Comment by gedankenstuecke** [comment]
Thanks for letting us know @joannearcilla! There was an issue with the mounting point for the data that's now fixed, you should be able to download both the full dump and individual files now! :)
