### ISSUE TITLE
Button "Download data" not working

### ISSUE THREAD

**Issue by rkarlssonlinner** [openSNP/snpr#540]
The button "Download data" gives:
404: Whatever you tried to access is not here.

The link https://opensnp.org/data/zip/opensnp_datadump.current.zip appears broken.

**Comment by gedankenstuecke** [comment]
Thanks for the report @rkarlssonlinner! It sometimes happens, i've kicked our server to recompile the file and hopefully within a few hours it should be available!

**Comment by philippbayer** [comment]
the link currently works, but i'll keep this issue open until we truly figure out what's going on

**Comment by haerang34** [comment]
hello. 
I'm having the same problem. :(
Please confirm this.

**Comment by tsujigiri** [comment]
I'm currently working on refactoring the worker. Until this is done, I commented out the part that is supposed to delete _old_ dumps and ran it. The dump can now be downloaded.

**Comment by gedankenstuecke** [comment]
Great, thanks @tsujigiri, I'll try to keep an eye on the file storage to make sure we don't run out of space again!
