### ISSUE TITLE
404 for openSNP data dump

### ISSUE THREAD

**Issue by brandonsaldan** [openSNP/snpr#553]
Same issue as #534 currently

**Comment by lovetcodes** [comment]
I am also getting this error. Is there any way we can find an archival version of the data dump?

**Comment by brandonsaldan** [comment]
> I am also getting this error. Is there any way we can find an archival version of the data dump?

@lovetcodes I've been looking on and off and haven't had any luck so far. If I find one I'll let you know here!

**Comment by philippbayer** [comment]
Sorry everybody! There seems to be a slightly unusual issue between the two servers. Usually when this happens data server and web server don't talk to each other, but they see each other and things are fine. Investigating!

**Comment by philippbayer** [comment]
In the meantime, there's an older dump from 2018: not good for current research but good enough to get parsers and some experimenting going 

https://zenodo.org/record/1442755#.XlTwyHVKh1M for this paper https://www.biorxiv.org/content/10.1101/2020.08.25.265900v1

**Comment by brandonsaldan** [comment]
@philippbayer Thanks so much for the archived version! Definitely going to help with what I need for now.

**Comment by tsujigiri** [comment]
Closing this as it seems to be resolved.

**Comment by philippbayer** [comment]
Thanks @tsujigiri!!! Looks like all it took was to manually kick the sidekiq server once (all i did is stop and start the sidekiq Docker, and to once manually re-enqueue the zipfulldata job). Apologies, I should've checked earlier

**Comment by xuchenyuan** [comment]
@philippbayer Hi, I was able to download openSNP data dump, but got 404 error these two days.
